library(gganimate)
library(ggplot2)
library(ggimage)
library(ggthemes)

options(gganimate.fps = 15)
# Trump Time Series
ggplot(data = YouGov_summ_Trump, mapping = aes(x=month_date, y = avg_pct)) + 
  geom_line(color = "red", alpha = 0.9) +
  geom_area(fill = "red", alpha = 0.4) +
  geom_image(aes(image = image), size = .15) +
  coord_cartesian(ylim=c(41,47)) + 
  ggtitle("Election Polls for Trump") + 
  theme_fivethirtyeight()+
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 27,
                                  family = "Benton Sans", face = "bold"),
        text=element_text(size=16,  family="Benton Sans"))+
  ylab("Result (%)") + 
  transition_reveal(month_date)
# Biden Time Series
ggplot(data = YouGov_summ_Biden, mapping = aes(x=month_date, y = avg_pct)) +
  geom_line(color = "cornflowerblue", alpha = 0.9) +
  geom_area(fill = "cornflowerblue", alpha = 0.4) +
  geom_image(aes(image = image), size = 0.16) +
  coord_cartesian(ylim=c(41,51)) +
  ggtitle("Election Polls for Biden") +
  theme_fivethirtyeight() +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 27,
                                  family = "Benton Sans", face = "bold"),
        text=element_text(size=16,  family="Benton Sans")) +
  ylab("Result (%)") + 
  transition_reveal(month_date) 
# Trump and Biden Time Series
ggplot(data = YouGov_summ_Biden, 
       mapping = aes(
         x=month_date, 
         y = avg_pct)
       ) +
  geom_line(color = "cornflowerblue", 
            alpha = 0.9) +
  geom_area(fill = "cornflowerblue", 
            alpha = 0.3) +
  geom_image(aes(image = image),
             size = 0.15) +
  coord_cartesian(ylim=c(41,51)) +
  geom_line(data = YouGov_summ_Trump,
            mapping = aes(
              x=month_date, y = avg_pct),
            color = "red", 
            alpha = 0.9) +
  geom_area(data = YouGov_summ_Trump, fill = "red", alpha = 0.3) +
  geom_image(data = YouGov_summ_Trump,aes(image = image),
             size = 0.15) +
  theme_fivethirtyeight() +
  ggtitle("2020 Presidential Election Polls") + 
  ylab("Result (%)") + 
  theme(plot.title = element_text(hjust = 0.5, size = 27, face = "bold"),
        text=element_text(size=16,  family="Benton Sans")) +
  transition_reveal(month_date)
